alerting:
  anomaly_threshold: 5
  email:
    enabled: false
    from: alerts@yourcompany.com
    password: your_app_password
    smtp_port: 587
    smtp_server: smtp.gmail.com
    to:
    - admin@yourcompany.com
    username: your_email@gmail.com
  enabled: false
  throttle_minutes: 15
  time_window_minutes: 5
  webhook:
    enabled: false
    headers:
      Content-Type: application/json
    url: https://hooks.slack.com/services/YOUR/WEBHOOK/URL
log_patterns:
- pattern: (?P<timestamp>\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}) (?P<level>ERROR|WARN|INFO|DEBUG)
    (?P<message>.+)
- pattern: (?P<timestamp>\d{4}/\d{2}/\d{2} \d{2}:\d{2}:\d{2}) (?P<level>\w+) (?P<message>.+)
ml_model:
  algorithm: isolation_forest
  contamination: 0.05
  max_features: 5000
  max_samples: auto
  n_components: 50
  n_estimators: 100
  ngram_range:
  - 1
  - 2
  random_state: 42
  use_hashing_vectorizer: false
  use_pca: true
monitoring:
  buffer_size: 1000
  check_interval: 1
  enabled: false
output:
  formats:
  - html
  - json
  - csv
  include_confidence_scores: true
  include_feature_importance: true
performance:
  chunk_size: 10000
  enable_caching: true
  max_workers: 4
  stream_buffer_size: 100
  use_memory_optimization: true
  use_parallel_parsing: true
report:
  include_raw_data: true
  max_anomalies_display: 100
  output_html: reports/anomaly_report.html
  template: default
  use_cache: true
report_columns:
- timestamp
- level
- message
- is_anomaly
- anomaly_score
- confidence
thresholds:
  anomaly_rate: 5
  error_count: 10
  warn_count: 20
